n_evil_frontend:
    resource: "@NEvilFrontendBundle/Controller/"
    prefix:   /
    type:     annotation

app:
    resource: "@NEvilUserBundle/Controller/"
    type:     annotation

lobby:
    resource: "@NEvilFrontLobbyBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"