security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: /login_check
                login_path: /login
                # csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /lobby

            logout:       true
            anonymous:    true

    access_control:
<<<<<<< HEAD
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lobby$, role: ROLE_USER}
=======
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
>>>>>>> bb42cde024c869398b3ab734d17cf8dbebc47ef7
        - { path: ^/admin/, role: ROLE_ADMIN }